// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OrderBook.Book
{

using global::System;
using global::FlatBuffers;

public struct Contract : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Contract GetRootAsContract(ByteBuffer _bb) { return GetRootAsContract(_bb, new Contract()); }
  public static Contract GetRootAsContract(ByteBuffer _bb, Contract obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Contract __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public float Price { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Contract> CreateContract(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      float price = 0.0f) {
    builder.StartObject(2);
    Contract.AddPrice(builder, price);
    Contract.AddName(builder, nameOffset);
    return Contract.EndContract(builder);
  }

  public static void StartContract(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddPrice(FlatBufferBuilder builder, float price) { builder.AddFloat(1, price, 0.0f); }
  public static Offset<Contract> EndContract(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Contract>(o);
  }
};


}
