// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OrderBook.Book
{

using global::System;
using global::FlatBuffers;

public struct Price : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Price __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Spot { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Open { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Close { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<Price> CreatePrice(FlatBufferBuilder builder, float Spot, float Open, float Close) {
    builder.Prep(4, 12);
    builder.PutFloat(Close);
    builder.PutFloat(Open);
    builder.PutFloat(Spot);
    return new Offset<Price>(builder.Offset);
  }
};


}
