// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OrderBook.Book
{

public enum Side : sbyte
{
 Buy = 0,
 Sell = 1,
 Short = 2,
};


}
