// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace QuestEngine.PlayerData
{

public enum Color : sbyte
{
 Red = 0,
 Green = 1,
 Blue = 2,
};


}
