// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace QuestEngine.PlayerData
{

public enum Equipment : byte
{
 NONE = 0,
 Weapon = 1,
};


}
