// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OrderBook.Book
{

public enum Strategies : byte
{
 NONE = 0,
 Contract = 1,
};


}
